### ISSUE TITLE
Not working on Sout East Asia Client

### ISSUE THREAD

**Issue by nqarubik** [CubE135/LoL-SkinAnalyst#1]
I use it on Riot VN client it doesn't work. can you update it?

**Comment by nqarubik** [comment]
![image](https://user-images.githubusercontent.com/31370784/213963928-562143d3-2b64-4708-b4da-571f2a3ad164.png)

**Comment by CubE135** [comment]
> I use it on Riot VN client it doesn't work. can you update it?

Hi :) What exactly is the "Riot VN client"?

**Comment by nqarubik** [comment]
it's LOL Southeast Asia

**Comment by CubE135** [comment]
Sadly, the app will not be able to work in Southeast Asia.
The reason for that is, that LOL is run by Garena in Southeast Asia.
They are completely separate from Riot so i cannot use the Riot API to connect to League of Legends.
For that reason, there is no way for my App to work in that region. Sorry :(

**Comment by nqarubik** [comment]
now it's completely moved over to Riot. Garena didn't release LOL anymore

**Comment by CubE135** [comment]
Oh, i see.
Then, the app should be working fine. Weird.
I will try to investigate.

**Comment by CubE135** [comment]
Ok, so i just downloaded the VN Client (South East Asia) and tried the app.
Works fine for me :/
![image](https://user-images.githubusercontent.com/8761463/216440625-13c7b7a9-92e3-49b7-9b26-44564a7420e1.png)


What Region & language are you using?

**Comment by nqarubik** [comment]
![image](https://user-images.githubusercontent.com/31370784/216503765-f8d75e7b-c246-4f81-86da-97f5281d580f.png)
I don't understand why it still doesn't work for me

**Comment by CubE135** [comment]
What Region and Language are you using?

**Comment by nqarubik** [comment]
Viet Nam and Vietnamese

**Comment by CubE135** [comment]
> Viet Nam and Vietnamese

When im installing League Of Legends, what do i need to choose here? There is no Vietnam here:
![image](https://user-images.githubusercontent.com/8761463/216820969-fdf7b2e2-1d4e-4db0-98a7-3657f60e9524.png)
![image](https://user-images.githubusercontent.com/8761463/216820997-bfb483bc-cd91-4af1-8345-39c8b0bcf270.png)

**Comment by nqarubik** [comment]
Scroll down and you'll see it eventually

Vào CN, 5 thg 2, 2023 lúc 8:13 CH Lasse Jacobsen ***@***.***>
đã viết:

**Comment by CubE135** [comment]
Look at my second Screenshot, i did scroll all the way down :)

**Comment by nqarubik** [comment]
https://lienminh.vnggames.com/dang-ky/
try it

Vào CN, 5 thg 2, 2023 lúc 8:18 CH Lasse Jacobsen ***@***.***>
đã viết:

**Comment by CubE135** [comment]
That is the one i downloaded and installed :P
Maybe i need a Vietnam VPN ^^

**Comment by nqarubik** [comment]
https://drive.google.com/file/d/1zwrKgqBTgiQEDX25CNWkx4awI53qB7MH/view?usp=sharing

**Comment by CubE135** [comment]
While League Of Legends is opened, can you open a terminal or CMD and run this command? And post a screenshot of the output?
`wmic process get Description | findstr /s "League"`

![image](https://user-images.githubusercontent.com/8761463/216825253-5f82a4a4-7a6a-49d0-ae56-940e731fc863.png)

**Comment by nqarubik** [comment]
![image](https://user-images.githubusercontent.com/31370784/216865537-4f58aa0d-8717-4841-a9ed-fd88a93df450.png)

**Comment by nqarubik** [comment]
![image](https://user-images.githubusercontent.com/31370784/216867914-d3b09723-e56d-4408-b6da-7e89f7be0175.png)

**Comment by nqarubik** [comment]
when i add path it worked. Thank you very much

**Comment by nqarubik** [comment]
it has a new problem
![image](https://user-images.githubusercontent.com/31370784/216868289-4c207dcd-02ff-43b1-8210-f60e7209e7f7.png)

**Comment by CubE135** [comment]
> when i add path it worked. Thank you very much

What path did you add? Where?

**Comment by nqarubik** [comment]
![image](https://user-images.githubusercontent.com/31370784/216894724-9de14888-5ce6-4396-ae60-9aa75c077c7d.png)

**Comment by CubE135** [comment]
Then, it looks like the problem might lay on your side of things.
I just published a new [Version](https://github.com/CubE135/LoL-SkinAnalyst/releases/tag/v1.0.4) of the App.
It allows you to view the console while running it.
You can try to do that to see if there are any errors in the console.
That is pretty much all i can do for you right now. :(
